version = 1

test_patterns = ["*_test.go"]

[[analyzers]]
name = "go"
enabled = true

[analyzers.meta]
import_paths = ["github.com/rhobro/wallmask"]

[[transformers]]
name = "gofmt"
enabled = true

[[transformers]]
name = "isort"
enabled = true
