version = 1

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_paths = ["github.com/rhobro/wallmask"]

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "sql"
enabled = true

[[transformers]]
name = "gofmt"
enabled = true

[[transformers]]
name = "isort"
enabled = true
