language: go
go:
  - 1.14.x
  - 1.15.x
  - 1.x

install:
  # get dependencies
  - go get -t -u -v ./cmd/wmidx
  # go cmd for coveralls
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - docker-compose up -d # test docker compose config
  - go test -race -v -coverprofile=coverage.txt -covermode=atomic ./... # unit tests for codecov

after_success:
  # codecov
  - bash <(curl -s https://codecov.io/bash)
  # coveralls
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.txt -service=travis-ci -repotoken $COVERALLS_TOKEN