language: go
go:
  - 1.12.x
  - 1.13.x
  - 1.14.x
  - 1.15.x
  - 1.x
  - master

install:
  - go get -u ./cmd/wmidx
  - go build -o bin/wmidx ./cmd/wmidx
  - docker-compose up -d

script:
  - go test ./...