language: go
go:
  - 1.13.x
  - 1.14.x
  - 1.15.x
  - 1.x
  - master

install:
  - go get -t -u -v ./cmd/wmidx

script:
  - docker-compose up -d # test docker compose config
  - go build -o bin/wmidx ./cmd/wmidx # test for error-free build
  - go test -coverprofile=coverage.txt -covermode=atomic ./... # unit tests TODO test for race

after_success:
  - bash <(curl -s https://codecov.io/bash) # upload coverage to CodeCov.io