version: "3"
services:
  cockroach:
    image: "cockroachdb/cockroach"
    container_name: "roachmaster"
    command: "start-single-node --insecure"
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - "/Users/mavicmaverick/cockroach-data:/cockroach/cockroach-data"
