CREATE TABLE prx_proxies
(
    id         INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    ipv4       VARCHAR(15) NOT NULL,
    port       INT,
    lastTested INT,
    working    BOOLEAN     NOT NULL
);
SELECT *
FROM prx_proxies
WHERE working = true
ORDER BY lastTested DESC;
SELECT *
FROM prx_proxies;
SELECT COUNT(*)
FROM prx_proxies;
DROP TABLE prx_proxies;

INSERT INTO prx_proxies (ipv4, port, lastTested, working)
VALUES ('', 2, 234, false);

UPDATE prx_proxies
SET lastTested = 0,
    working    = false
WHERE id = 0;

SELECT table_name
FROM sysibm.tables
WHERE table_schema = 'LZX36405';

SELECT id
FROM prx_proxies
WHERE ipv4 = '100.24.216.83'
  AND port = 80;
